apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: alert-receiver
    version: v1
  name: alert-receiver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: alert-receiver
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alert-receiver
        version: v1
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --config=/config/collector.yml
          image: docker.io/otel/opentelemetry-collector-contrib:0.121.0
          imagePullPolicy: IfNotPresent
          name: otel
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 50514
              protocol: TCP
            - containerPort: 50514
              protocol: UDP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config/collector.yml
              name: collector
              readOnly: true
              subPath: collector.yml
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_SPAN_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: SRV_NAME
                  name: instance
            - name: OTEL_PROTOCOL
              value: grpc
            - name: WEB_CONCURRENCY
              value: '5'
            - name: TZ
              value: UTC
          image: localhost/alert-webhook-to-trace
          imagePullPolicy: IfNotPresent
          name: alert-receiver
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '500m'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 3
      volumes:
        - configMap:
            defaultMode: 420
            name: collector
            optional: true
          name: collector
