apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traces-writer-user-alerts-to-traces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traces-writer-user
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traces-writer-user
rules:
  - apiGroups:
      - tempo.grafana.com
    resourceNames:
      - traces
    resources:
      - user
    verbs:
      - create
